FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN go mod download

COPY . .

# CGO_ENABLED=0 确保交叉编译成静态可执行文件，能在 alpine 中直接运行
RUN CGO_ENABLED=0 GOOS=linux go build -o /qauth-server ./main.go

FROM alpine:latest
ARG PORT=8080

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /qauth-server .
COPY --from=builder /app/.env . 

EXPOSE ${PORT}

CMD ["./qauth-server"]