import type { AuditAction } from '@/types'

export const actionNamesMapping: Record<AuditAction, string> = {
   LOGIN: '登录',
   LOGOUT: '登出',
   REGISTER: '注册',
   PASSWORD_RESET: '密码重置',
   PASSWORD_CHANGE: '密码修改',
   TOKEN_REFRESH: '令牌刷新',
   OAUTH_AUTHORIZE: 'OAuth授权',
   OAUTH_TOKEN: 'OAuth令牌',
   OAUTH_REVOKE: 'OAuth撤销',
   CLIENT_CREATE: '创建客户端',
   CLIENT_UPDATE: '更新客户端',
   CLIENT_DELETE: '删除客户端',
   ROLE_CREATE: '创建角色',
   ROLE_UPDATE: '更新角色',
   ROLE_DELETE: '删除角色',
   PERMISSION_CREATE: '创建权限',
   PERMISSION_UPDATE: '更新权限',
   PERMISSION_DELETE: '删除权限',
   PERMISSION_GRANT: '授予权限',
   PERMISSION_REVOKE: '撤销权限',
   USER_CREATE: '创建用户',
   USER_UPDATE: '更新用户',
   USER_DELETE: '删除用户',
   KEY_ROTATION: '密钥轮换',
   SETTINGS_CHANGE: '设置变更',
   APP_GROUP_ROLE_CREATE: '创建应用组角色',
   APP_GROUP_ROLE_UPDATE: '更新应用组角色',
   APP_GROUP_ROLE_DELETE: '删除应用组角色',
   APP_GROUP_ROLE_ASSIGN_PERMISSIONS: '分配应用组角色权限',
   APP_GROUP_ROLE_REVOKE_PERMISSIONS: '撤销应用组角色权限',
   APP_GROUP_USER_ASSIGN_ROLES: '分配应用组用户角色',
   APP_GROUP_USER_REVOKE_ROLES: '撤销应用组用户角色',
   APP_GROUP_ADMIN_ADD: '添加应用组管理员',
   APP_GROUP_ADMIN_REMOVE: '移除应用组管理员',
   APP_GROUP_PERMISSION_CREATE: '创建应用组权限',
   APP_GROUP_PERMISSION_UPDATE: '更新应用组权限',
   APP_GROUP_PERMISSION_DELETE: '删除应用组权限',
   APP_GROUP_ROLE_PERMISSIONS_SET: '设置应用组角色权限',
}
